version: '3.11'

services:
  mcp-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=INFO
    volumes:
      - ./docs:/app/docs
    restart: unless-stopped
