name = "document-automation-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
MCP_SERVER_NAME = "document-automation-server"
MCP_SERVER_VERSION = "1.0.0"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "mcp-server-db"
database_id = "a954605d-4a0a-4852-aab9-d981aea8c56e"

# R2 Bucket binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "mcp-documents"

# AI binding
[ai]
binding = "AI"

# Durable Objects binding
[[durable_objects.bindings]]
name = "MCP_SESSION"
class_name = "MCPSession"

# Migrations - CHANGED FOR FREE PLAN
[[migrations]]
tag = "v1"
new_sqlite_classes = ["MCPSession"]  # Changed from new_classes to new_sqlite_classes